---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: issasahbi
    password: 123321...

- name: Tag and push to docker hub
  docker_image:
    name: angular:latest
    repository: issasahbi/devops
    tag: end
    push: yes